openapi: 3.0.0
info:
  title: Minimal API
  version: 1.0.0
  description: A very basic API with a single resource.
servers:
  - url: http://localhost:3000/api/minimal # Assuming server runs on 3000 and spec is named 'minimal'

components:
  schemas:
    Item:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        name:
          type: string
          example: "My Minimal Item"
        description:
          type: string
          example: "This is a simple item."

paths:
  /items:
    get:
      summary: List all items
      operationId: listItems
      responses:
        "200":
          description: An array of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      summary: Create an item
      operationId: createItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: Item created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"

  /items/{itemId}:
    parameters:
      - name: itemId
        in: path
        required: true
        description: ID of the item to retrieve
        schema:
          type: string
          format: uuid
    get:
      summary: Get an item by ID
      operationId: getItemById
      responses:
        "200":
          description: The item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found
